version: "3.0"
services:
  es:
    container_name: topic_classification_elaticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  web-app:
    container_name: topic_classification_service
    build: .
    ports:
      - 8080:8080
    depends_on:
      - es
